### ISSUE TITLE
Modal on open doesn’t fire

### ISSUE THREAD

**Issue by 343dev** [rexrainbow/phaser3-rex-notes#341] opened 2023-03-06 15:34 UTC
Hi there.

Since v1.1.79 the “open” event doesn’t fire when modal `duration.in` is set to zero.

https://codepen.io/343dev/pen/BaOdpXm

**Comment by rexrainbow** [comment] 2023-03-07 01:59
Thanks, this issue has been fixed in latest commit. 

The root cause is, modal behavior opens dialog game object too early before registering 'open' event. 
Now the modal will open dialog next tick after creating this modal behavior.

**Closed** 2023-03-09 01:29 UTC
Labels: bug
